/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cricproject;

import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Rafee
 */
public class adminForm extends javax.swing.JFrame {

    private int selectedData,col_no;
    private String conn_string = null;
    private String query = null;
    private String user, pass, dbName;
    private String deleteVal, table_Name, col_name,updateVal,updateColumnName;
    private String[] col_names;
    
    private TableModel model = null;
    
    DatabaseHandler ob1 = new DatabaseHandler();

    public adminForm() {
        initComponents();
        
        ob1.setConnection();
    
        dbTable_Name.removeAllItems();
        
        ArrayList<String> table;
        
        table = ob1.showtable();

        for (int i = 0; i < table.size(); i++) {
            dbTable_Name.addItem(table.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbTable_Name = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        dbTable = new javax.swing.JTable();
        dbTable_Show = new javax.swing.JButton();
        deleteData = new javax.swing.JButton();
        addColumnBttn = new javax.swing.JButton();
        closeBttn = new javax.swing.JButton();
        deleteColumnBttn = new javax.swing.JButton();
        insertBttn = new javax.swing.JButton();
        updateBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dbTable_Name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        dbTable_Name.setToolTipText("");
        dbTable_Name.setAutoscrolls(true);

        dbTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dbTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dbTable);

        dbTable_Show.setText("Show All");
        dbTable_Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbTable_ShowActionPerformed(evt);
            }
        });

        deleteData.setText("Delete");
        deleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDataActionPerformed(evt);
            }
        });

        addColumnBttn.setText("Add Column");
        addColumnBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addColumnBttnActionPerformed(evt);
            }
        });

        closeBttn.setText("Close");
        closeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBttnActionPerformed(evt);
            }
        });

        deleteColumnBttn.setText("Delete Column");
        deleteColumnBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteColumnBttnActionPerformed(evt);
            }
        });

        insertBttn.setText("Insert");
        insertBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBttnActionPerformed(evt);
            }
        });

        updateBttn.setText("Update");
        updateBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(insertBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(dbTable_Show, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteData, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(deleteColumnBttn)
                        .addGap(18, 18, 18)
                        .addComponent(addColumnBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dbTable_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(521, 521, 521)
                        .addComponent(closeBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(closeBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(dbTable_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteColumnBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addColumnBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteData, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbTable_Show, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBttn))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dbTable_ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbTable_ShowActionPerformed
        ResultSet result = ob1.showAllDataQuery(dbTable_Name.getSelectedItem().toString(),null,null,0);
        
        dbTable.setModel(DbUtils.resultSetToTableModel(result));
        
        table_Name = dbTable_Name.getSelectedItem().toString(); 
        
        col_no = dbTable.getColumnCount();
        
        col_names = new String[col_no + 1];
        
        JTableHeader th = dbTable.getTableHeader();
        
        TableColumnModel tcm = th.getColumnModel();
        
        for(int x = 0, y = tcm.getColumnCount(); x < y; x++)
        {
          TableColumn tc = tcm.getColumn(x);
          col_names[x] =  tc.getHeaderValue().toString();
        }
    }//GEN-LAST:event_dbTable_ShowActionPerformed

    private void dbTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbTableMouseClicked
        selectedData = dbTable.getSelectedRow();

        model = dbTable.getModel();

    }//GEN-LAST:event_dbTableMouseClicked

    private void deleteDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDataActionPerformed
         if (model != null) {
            deleteVal = model.getValueAt(selectedData, 0).toString();

            //table_Name = dbTable_Name.getSelectedItem().toString();

            col_name = model.getColumnName(0);

            ob1.deleteData(table_Name, col_name, deleteVal);
        }
    }//GEN-LAST:event_deleteDataActionPerformed

    private void addColumnBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addColumnBttnActionPerformed
        
        addColumn ob2 = new addColumn(ob1);
        
        ob2.setTableName(table_Name);
        
        ob2.setVisible(true);
    }//GEN-LAST:event_addColumnBttnActionPerformed

    private void closeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBttnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBttnActionPerformed

    private void insertBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBttnActionPerformed
        insertForm ob2 = new insertForm(table_Name, col_no,col_names,ob1);
        
        ob2.setVisible(true);
        
    }//GEN-LAST:event_insertBttnActionPerformed

    private void deleteColumnBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteColumnBttnActionPerformed
        
        deleteColumnFrame ob2 = new deleteColumnFrame(table_Name, col_no,col_names,ob1);
        
        ob2.setVisible(true);
    }//GEN-LAST:event_deleteColumnBttnActionPerformed

    private void updateBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBttnActionPerformed
        try{
        
        if(model != null){
            updateVal = model.getValueAt(selectedData, 1).toString();
            
            updateColumnName = model.getColumnName(1);
            
            updateFormAdmin ob2 = new updateFormAdmin(table_Name, col_no, col_names, ob1, updateVal, updateColumnName);
            
            ob2.setVisible(true);
        }
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addColumnBttn;
    private javax.swing.JButton closeBttn;
    private javax.swing.JTable dbTable;
    private javax.swing.JComboBox<String> dbTable_Name;
    private javax.swing.JButton dbTable_Show;
    private javax.swing.JButton deleteColumnBttn;
    private javax.swing.JButton deleteData;
    private javax.swing.JButton insertBttn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateBttn;
    // End of variables declaration//GEN-END:variables
}
